server:
  port: 8080 # 后端运行在 8080

spring:
  datasource:
    # ?? ??????? '??'?? MySQL ????
    url: jdbc:mysql://localhost:3306/低碳?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis Plus ?? (?????? SQL?????)
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # ??????? user_id ?? Java ? userId
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl